/**
 * Swagger First Rest Api 文档
 * user 模块api文档
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BaseResultstring { 
    data?: string;
    message?: string;
    status?: number;
}
