/**
 * Swagger First Rest Api æ–‡æ¡£
 * user æ¨¡å—apiæ–‡æ¡£
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PersonalCalanderDto { 
    backgroundColor?: string;
    borderColor?: string;
    changeFlg?: boolean;
    end?: Date;
    id?: number;
    start?: Date;
    title?: string;
    userId?: number;
}
